version: '3.8'

services:
  opengrok:
    image: opengrok/docker:latest
    container_name: codemcp-opengrok
    ports:
      - "8080:8080"
    volumes:
      # Mount individual projects directly
      # Add your projects here:
      - /Users/mustafaacar/retter/shortlink:/opengrok/src/shortlink:rw
      - /Users/mustafaacar/codemcp:/opengrok/src/codemcp:rw
      # Add more projects as needed by following this pattern:
      # - /path/to/your/project:/opengrok/src/project-name:ro

      # Persist OpenGrok data between restarts
      - opengrok-data:/opengrok/data
      - ./mirror.yml:/opengrok/etc/mirror.yml:ro
      # Custom configuration
      - ./logging.properties:/opengrok/etc/logging.properties:ro
    environment:
      # Indexing options with automatic project detection
      # -H: Generate history cache
      # -P: Generate a project for each top-level directory in source root
      # NOTE: -S and -G flags removed to fix "You must select a project!" error
      # These flags require write access for git operations on read-only mounts
      # -H (history) is disabled because it can cause issues with read-only git repos.
      - INDEXER_OPT=-P -i node_modules -i cdk.out
      - REINDEX=1
      - SYNC_PERIOD_MINUTES=60  # re‑run every hour
      # Number of indexer threads
      - INDEXER_THREADS=4
      # JVM memory settings
      - JAVA_OPTS=-Xmx2g -Xms512m
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/system/ping || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

volumes:
  opengrok-data:
    name: codemcp-opengrok-data
